name: Update the flake inputs
on:
  schedule:
  - cron: '0 0 * * *'
jobs:
  update-inputs:
    runs-on: ubuntu-latest
    steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v16
    - uses: actions/checkout@v2
    - name: configure git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    - name: update inputs in the lock file
      run: nix flake lock --commit-lock-file --update-input alot
    - name: build the alot package
      run: "nix build .#alot"
    - name: push changes back to the repository
      run: git push
